### ISSUE TITLE
store total number of epochs

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#110]
involves also keeping images with `image_flags` in the `epochs_info`

**Comment by esheldon** [comment]
it looks like images with `image_flags` are also not kept in the `image_info` extension

**Comment by beckermr** [comment]
:(

**Comment by esheldon** [comment]
sorry, not true, they are in `image_info`

**Comment by beckermr** [comment]
closing this since we decided to not worry about it.
