### ISSUE TITLE
read pixmappy not from piff

### ISSUE THREAD

**Issue by beckermr** [beckermr/pizza-cutter#111]

**Comment by esheldon** [comment]
this means we'll actually have to 1) learn how to do that 2) copy the astrom files wherever

**Comment by beckermr** [comment]
Hrmmmm. So if we want to record the total possible number of epochs, then we need the pixmappy astrometry even if the piff solution is not to be used. Does piff always have a file, even if the PSF is on the balcklist? In this case, we can read it anyways.

**Comment by esheldon** [comment]
Not all exposures get a piff file because some are blacklisted before piff runs.

Maybe Let's not worry too much about this total possible number of epochs.

**Comment by beckermr** [comment]
Yeah not worrying seems better TBH. Closing.
