### ISSUE TITLE
add the current MEDS_DIR, DESDATA and any other relevant env vars to the MEDS file

### ISSUE THREAD

**Issue by beckermr** [beckermr/pizza-cutter#113]
These can be really useful when munging paths

**Comment by esheldon** [comment]
this makes the config files not portable.

The idea of using env vars was to make everything portable to a new site.  All one needs to do is make sure those vars are defined

by the way, the way the info files is currently being stored breaks this model; should be using paths like this

```
$MEDS_DIR/des-pizza-slices-y5/DES0406-5414/sources-i/OPS/finalcut/Y5A1/r3650/20130912/D00233634/p01/psf/D00233634_i_c31_r3650p01_psfexcat.psf
```

**Comment by esheldon** [comment]
(then use `os.path.expandvars()` when using the paths )

**Comment by beckermr** [comment]
I mean add this info to the MEDS file, not the config file. And yes, this is exactly what I would like to fix with the paths.
