### ISSUE TITLE
cut on max area masked by STAR (32)?

### ISSUE THREAD

**Issue by beckermr** [beckermr/pizza-cutter#114]
A cut of 1/3 or so would eliminate really nasty slices where a lot of the area is not usable.

**Comment by esheldon** [comment]
We could reserve such a cut until later, after processing.

Is such a cut afterward still straightforward with the overlap of patches?

**Comment by beckermr** [comment]
Yes in the sense that we can remove a single region of sky without ambiguity. Cutting all data from a single SE image is also possible afterwards but is more intrusive.

**Comment by esheldon** [comment]
My worry is about when we merge patches.  Is there a possibility we could merge and then not have cancellations if we start removing data?

**Comment by beckermr** [comment]
Ahhhh. IDK. The patches right now have a core of 250 pixels with a buffer of 125 on each side. I plan to cut the 125 pixel buffers. I am not sure how this will all work out.

**Comment by esheldon** [comment]
Yeah.   Just to be explicit, I worry we may be breaking the symmetry some how when things like buffers interact with other cuts.

**Comment by esheldon** [comment]
we will leave this cut to be done on the metadetect catalogs
