### ISSUE TITLE
all negative weight maps

### ISSUE THREAD

**Issue by beckermr** [beckermr/pizza-cutter#119]
It appears the weight maps in the meds files are all negative which is why the code is failing.

**Comment by beckermr** [comment]
By code I mean the code to run metadetect.

@esheldon for viz

**Comment by beckermr** [comment]
I do not see this on a y3 meds file I just made locally. I am going to test a y5 one too.

**Comment by beckermr** [comment]
I don't see it on my local y5 file either. Maybe your fits file is corrupted?

**Comment by beckermr** [comment]
This is the cause of #118 btw.

**Comment by esheldon** [comment]
I remade a meds file from scratch, and now all the weights are negative.  So i think this is a real issue

**Comment by esheldon** [comment]
turns out all the weights are `nan` and then when this gets fpacked it is being turned into about `-2.6` but with the usual random noise on top

**Comment by esheldon** [comment]
the nan is coming from the `lanczos` resampling.  This means the image will also have these fpacked `nan` turned to about `-2.6`

**Comment by esheldon** [comment]
I think the answer here is to replace the `nan` with zero and set a bit

**Comment by esheldon** [comment]
Maybe we should just let the resampling do its thing, don't set nan, but set a bit.

**Comment by beckermr** [comment]
So the nans from the resampling are for cases where it is not possible because the input image doesn't have any pixels that could be used to resample the at the requested location. This should be quite rare, but NaNs are viral. :(

I think we should do the following, which is similar to what you suggested above.

1. Let the resampling give NaN.
2. Use `np.nanvar` to compute the noise variance.
2. Set any NaN values to zero, set the weight to zero in that area, and set a bit in the bmask. I think BMASK_EDGE is the correct bit to set and is already used for similar things.

**Comment by esheldon** [comment]
I've got a PR #121 in, might not be quite ready yet

by letting lanczos do its thing we get "natural" values for the noise even though they are not quite right

**Comment by beckermr** [comment]
closing.
