### ISSUE TITLE
reduce max box size for moments only metadetect

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#124]
our weight function is 1.2'' which is a sigma of about 2 pixels.  So a box size of `2*2*5=20` pixels would be sufficient.  We can round up to 32

**Comment by beckermr** [comment]
Do you mean in the code, or simply changing the config file?

**Comment by beckermr** [comment]
The configs in the repo are meant to be examples. Presumably, real configs with versions will exist elsewhere.

**Comment by esheldon** [comment]
yep, just putting a reminder here for myself
