### ISSUE TITLE
deal with None observations returned when running metadetect

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#125]
and understand why they are coming back None in this case; seems that should not happen for these large patches

**Comment by beckermr** [comment]
We could not find any input images for a patch, especially near edges of the survey. Also the meds readers reject zero or negative weight images. I think we need to simply test for None and move on.

**Comment by esheldon** [comment]
yeah, that is all reasonable. We should probably have a look at some to make sure nothing funny is going  on.
