### ISSUE TITLE
arr.dat are being left behind

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#144]
I'm seeing a lot of these tmpdirs left over with arr.dat in them

```
[esheldon@astro0036 tmp] ls -d tmp*
tmp01975a47  tmp2x95ekh8  tmp5b1kmso8  tmp7f4098_5  tmp9b9pu00o  tmpbagl8xux  tmpe2v6k_8z  tmpfwnxrmiq  tmpio_bo2y9  tmpky3yfjg4  tmpmpqwtiks  tmpqnpedsep  tmpt2g8ssk5  tmpv5km189z  tmpvw_mqpey  tmpyb76faq8
tmp05f982mc  tmp2xgiwu16  tmp5ehuuwlg  tmp7f78b8wi  tmp9cza1zws  tmpb_jzvqp6  tmpeb3ucd6x  tmpgb14b3eo  tmpj5bkpdxw  tmpl5y12qwb  tmpn7nm4qk3  tmpqpw1anhg  tmpt8q91gsh  tmpvam55wo1  tmpw80hffga  tmpyc6nrao_
tmp0fccv0zd  tmp_336oi5x  tmp5ignd7rk  tmp7_p90uld  tmp9gfim1fv  tmpbk0asq02  tmpeboxa2ti  tmpgj0n91v1  tmpj7q4k0lf  tmplb_s35qb  tmpofo7rv9a  tmpr7hoz7at  tmptjpayw5b  tmpvd4nsuap  tmpwv_s22pu  tmpymni_kbp
tmp0kdpxd30  tmp_3ka7vfg  tmp5p_215xx  tmp7xqlhic2  tmp9k6gjwvw  tmpbrk7gwt8  tmpejnc5c2q  tmpgp5pebv_  tmpj8om0ur5  tmplcwq29qn  tmpoksw3f4y  tmprmr2dx2i  tmptsmrlro8  tmpvj0iuev_  tmpx8tyci2d  tmpyr20d1hi
tmp0ncai7yb  tmp3p51w00r  tmp5w63o048  tmp8232i8uu  tmp9r782gjf  tmpcbwk_7u9  tmpel4os1q9  tmpgq2p6gr5  tmpj9tihlnr  tmpl_f47o_b  tmp_orlv2pz  tmpro6qkpxs  tmptx0skrl8  tmpvkmxxf9_  tmpx9eupvlz  tmpyxh3sdwp
tmp0w5ib2ni  tmp4pkhtb8e  tmp67r6fyqc  tmp874mqq96  tmp9v0nooeo  tmpcpf_fdj0  tmpf0xhx30k  tmpgqo6glvb  tmpjdt88imd  tmplpblp5hu  tmp_p9ef23a  tmprs1hfssn  tmptyjkspxs  tmpvooy795t  tmpx9uohvdu  tmpzlmwib6m
tmp1eq583z0  tmp4rq1ag4w  tmp6pb4h778  tmp87wpb9wk  tmpa4ns0l4s  tmpdcb_mpaj  tmpfcdxwynp  tmpgwjx_utx  tmpjkggq_rv  tmplxfca0ui  tmppqt8ee1f  tmps9rat7rr  tmptyr9ld7u  tmpvqe5jef1  tmpxmhil6c2  tmpznu2e34i
tmp1j2djw6t  tmp4xhtl8a9  tmp6wfsc5ae  tmp89wsv6ae  tmpa4se7noy  tmpdfgf94vg  tmpfqe4uu32  tmph0oqptrf  tmpjm6cf2n0  tmpm2wzv_s8  tmppynthlj9  tmpsbznfq2s  tmpu1oov1g7  tmpvr57jmwl  tmpxsqkyji7
tmp1th8ntb1  tmp4za3zn5y  tmp6xqk2qvv  tmp8r8tvefc  tmpaiejml5s  tmpdgh5mdx2  tmpfru0zz89  tmphmuimdom  tmpjt6tl5wf  tmpm8lg497p  tmpqflfer2q  tmpszm7f48u  tmpun2jz99k  tmpvs6a58oc  tmpxwan628i
tmp23qwerod  tmp4zu6bxh1  tmp72y9xjg2  tmp8ud4g925  tmpas5iz9qd  tmpdhp3rtd2  tmpfuf55yxd  tmphuidmfvb  tmpj_u5yyq8  tmpmkj4d3b8  tmpqj6bfecj  tmpt08cw7ps  tmpuq2ulkz0  tmpvs6hinmn  tmpxy4de3i1
tmp2su3kjiw  tmp57i20l2m  tmp7dhi_flq  tmp_8uyij4f  tmpb90kcnnh  tmpdvniujjg  tmpfvo02ujb  tmpi1u5nemo  tmpjv7l7a4o  tmpmml7eu1g  tmpqmtwxyno  tmpt0v9dntg  tmpuw3js_o7  tmpvvob06wh  tmpyas1esp0
```

**Comment by beckermr** [comment]
These might be from the noise fields?

**Comment by beckermr** [comment]
I am using this call: https://github.com/beckermr/pizza-cutter/blob/master/pizza_cutter/memmappednoise.py#L44

According to the docs, it should all get cleaned up when things are deleted at the end of the python session

>>> This function securely creates a temporary directory using the same rules as mkdtemp(). The resulting object can be used as a context manager (see Examples). On completion of the context or destruction of the temporary directory object the newly created temporary directory and all its contents are removed from the filesystem.

**Comment by beckermr** [comment]
Otoh I should know better than to rely on effectively __del__ for cleanup. :/

**Comment by beckermr** [comment]
everything is cleaned up locally on my machine...

**Comment by esheldon** [comment]
what if the process is killed?

**Comment by beckermr** [comment]
I tried that locally and it was still cleaned up.

**Comment by esheldon** [comment]
I'm still seeing these everywhere, maybe a difference from mac os x and linux?

**Comment by beckermr** [comment]
Yup could be. Or GPFS? In any case, we should fix.

**Comment by esheldon** [comment]
the temp files are on local disk.  I've seen it on ext3 on our cluster spinning disks, as well as ext4 ssd on my desktop

**Comment by beckermr** [comment]
mmmk - well a context manager is going to be really hard in this case. Maybe we cache the dirs and then use a signal handler or at exit to clean them up at the end?

**Comment by esheldon** [comment]
We could always put everything under `$TMPDIR/pizza-{some-unique-string}`

Then we have runs in a try finally block and clean up that directory.

Or the equivalent with some other method like a signal handler, but the above seems easier to grok

**Comment by beckermr** [comment]
Right. We should at least use the python built-in method as a context manager if we are going to enforce a global temp dir in a tryfinally block

```import tempfile

with tempfile.TemporaryDirectory() as tmpdir:
    # do something
```

**Comment by beckermr** [comment]
Do we need this still?
