### ISSUE TITLE
store slice_data extension

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#147]
can contain

- slice_id
- flags
- fraction of slice masked
- fraction of slice masked by STAR
- other?

**Comment by esheldon** [comment]
for metadetect

**Comment by esheldon** [comment]
gonna add these instead to the object data for now, which means they are redundant but more convenient

**Comment by esheldon** [comment]
Propose the following masking entries
```
star_frac: fraction of slice that had STAR set.  Should this be fraction without overlaps?
imperfect_frac: fraction that was interpolated or had STAR or TAPEBUMP set
```

**Comment by esheldon** [comment]
note this code will actually go in metadetect

**Comment by beckermr** [comment]
Hmmmm. I think maybe we add more basic things and then do other cuts in post-processing? My thought is that someday this will all see the light of day and then people will be confused. How about

star_frac: STAR or TRAIL
spline_interp_frac: the spline interp bit in the bit mask
noise_interp_frac: the noise interp bit in the bit mask
tapebump_frac: TAPEBUMP

We cannot just add these together to get back your proposed things though.

**Comment by esheldon** [comment]
The STAR and TRAIL will be present for all epochs and bands

The more epochs we add, the others become less important.  I will add them but I think they might not be as useful as we get closer to 10 epochs per band

**Comment by beckermr** [comment]
happy to defer to your judgment OFC - just wanted to say something before we decided

**Comment by esheldon** [comment]
working on this in metadetect, so closing this issue
