### ISSUE TITLE
cache not large enough for some real examples

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#148]
For some real DES tiles I found the cache was too small.

e.g. tile `DES0332-5331` has 247 images associated with it so the current cache sizes are useless.  The run time was going to be > 24 hours.

I upped some of the caches as a test and got it down to 4-5 hours (see branch cacheproblem) but memory when from 2G to 5-6G.  Using bigger caches would have helped.

**Comment by beckermr** [comment]
I guess we might want to write a two-layer cache that also uses disk. :(

**Comment by beckermr** [comment]
At least for some things. We could switch to using FITS objects for the i/o which will help as well, but I am guessing the time sink is the WCS stuff.

**Comment by esheldon** [comment]
it could be; I didn't run all permutations, I just upped caches on a lot of things

**Comment by beckermr** [comment]
I think this is largely solved or at least we've decided to punt by not doing anything. Closing for now.
