### ISSUE TITLE
use fitsio images on disk to cache the noise fields

### ISSUE THREAD

**Issue by beckermr** [beckermr/pizza-cutter#168]
We should be doing this instead of using the memmapped arrays. Right now if we have a cache miss, the noise image is remade and it is not well determined when the disk data will get cleaned up.

**Comment by beckermr** [comment]
@esheldon What was the motivation for this? Are we ok leaving FITS files open?

**Comment by esheldon** [comment]
I don't know if a memmapped file or a fits file is better in general. The FITS file doesn't hold on to a reference to any memory, so maybe that is a motivations.

**Comment by beckermr** [comment]
I am going to close this. The code is running pretty well without it.
