### ISSUE TITLE
use large PIFF postage stamps

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#190]
I think mike recommended 25x25

**Comment by esheldon** [comment]
We should do this before we hand off code to DESDM

**Comment by beckermr** [comment]
We use 21 pixels right now.

https://github.com/beckermr/pizza-cutter/blob/master/pizza_cutter/des_pizza_cutter/_se_image.py#L751

**Comment by esheldon** [comment]
- should it be configurable?
- Is there a unit test testing 21?

**Comment by beckermr** [comment]
Yes, I wrote tests. :)

We have at least this

https://github.com/beckermr/pizza-cutter/blob/master/pizza_cutter/des_pizza_cutter/tests/test_se_image_psf.py#L162

The integration tests may have some dependence on this too. I have not checked.

We could make it configurable, but I wrote this code just for DES so I figured we'd only have to set this once.

**Comment by beckermr** [comment]
Looks like the integration test only uses a Gaussian PSF.

**Comment by esheldon** [comment]
I see this got changed to 25 somewhere along the line.  I don't know if its large enough or not.  Maybe we should add another issue to try to figure out what's the right size

**Comment by beckermr** [comment]
SGTM!
