### ISSUE TITLE
numpy warning

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#191]
VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  phat = numpy.array([-1.0*sinp,cosp,0.0]).T

**Comment by esheldon** [comment]
this is actually in the meds code...

**Comment by beckermr** [comment]
Woops. :(

**Comment by esheldon** [comment]
do you know what's going on there?  arrays for the first two plus the scalar 0.0?

**Comment by beckermr** [comment]
no idea

**Comment by beckermr** [comment]
I made a PR on the meds repo to fix this. I am closing the issue here.
