### ISSUE TITLE
should pytest be in requirements?

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#193]

**Comment by beckermr** [comment]
It is not imported unless we are running the tests, but sure we can add it.

**Comment by esheldon** [comment]
It is not a cheap dependency, pulls in a lot of other stuff.

**Comment by esheldon** [comment]
not sure if desdm has that stuff already in their stack, for example

**Comment by beckermr** [comment]
closing as we do not need it right now
