### ISSUE TITLE
purpose?

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#2]
What's the purpose of this library?

If it is to make coadds in cells I think we should start *very* small, with a specific case rather than getting general.

**Comment by beckermr** [comment]
I just want a place to put code with tests. We don't have to use it in the end.

**Comment by beckermr** [comment]
closing but happy to discuss more!

**Comment by esheldon** [comment]
ahh, ok.  I thought with such a particular name that you might have great expectations for this package :)

**Comment by beckermr** [comment]
Nope. ;p Just having fun...
