### ISSUE TITLE
figure out the best piff stamp size

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#202]
Is larger better?

**Comment by esheldon** [comment]
Mike has said that if large stamps are used, it will fill with zeros in any region where there is no information from the fitting.

That would potentially mean discontinuities in the profile.

For the FFTs the stamps get padded with zeros anyway and we have not seen problems with that in the past.  But I think those tests were potentially with more compact PSFs

**Comment by beckermr** [comment]
@esheldon Do we want to apodize the edges of the Piff models for FFTs? the outskirts are always noisy but consistent with zero so I don't think we'll need this.

**Comment by esheldon** [comment]
I really don't have a clue

**Comment by beckermr** [comment]
I am going to close this for now. My best guess is that we will be fine, consistent with other tests @esheldon and I have done.
