### ISSUE TITLE
all slices are getting masked the same for gaia stars

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#229]
the exact same pixels are always getting masked.  Presumably this is because x/y are not correct

@beckermr You advised that we could cache x/y in the first call, could this be the problem?

**Comment by esheldon** [comment]
maybe I need to be adding start_row, start_col to the x, y used for calculating radius to the star

**Comment by beckermr** [comment]
We can cache ra-dec to x-y for the full coadd wcs. To get to local coords on the slice you need to remove orig start row and orig start col

**Comment by beckermr** [comment]
Yep. It looks like we forgot the offset to slice coords.

**Comment by beckermr** [comment]
Looks like the code missed removing the wcs position offset too.

**Comment by beckermr** [comment]
Sorry for the bad code review. :/

**Comment by esheldon** [comment]
sorry, what needs to be done for wcs position offset?

**Comment by beckermr** [comment]
When we convert from ra dec to x y when reading the stars, we need to subtract the input variable wcs_position_offset. This is input to the calling functions and should be around.

**Comment by esheldon** [comment]
I'll have an update soon.

to test this we need a sim with more than one slice

**Comment by beckermr** [comment]
Yup. That's probably why we missed it.

**Comment by esheldon** [comment]
noticing that these star masks are not getting symmetrized

**Comment by esheldon** [comment]
locations looking OK, but we clearly need to expand them

![bmask-01019](https://user-images.githubusercontent.com/621661/113168330-8e560200-9212-11eb-91ba-c2f49a4156f2.png)

**Comment by beckermr** [comment]
If you want then symmetrized they will need to be injected way earlier in the code.

**Comment by esheldon** [comment]
I'll just make a new bmask for this,  symmetrize it, and then  "or" it with the bmask produced by the coadding

**Comment by beckermr** [comment]
Cool. I have a canned function for symnetrizing masks if you want to use it.

**Comment by esheldon** [comment]
yep, found it, thanks

**Comment by beckermr** [comment]
Is the plan to renterpolate these regions before running metadetect?

**Comment by beckermr** [comment]
I'm asking because we got very little traction on using these coadds for the whole Y6 analysis so we could consider just doing all of that here.

**Comment by esheldon** [comment]
Good point, this needs to be done after we coadd.
