### ISSUE TITLE
interpolate bright star masks

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#230]
this happens after coadding

Should this be in pizza cutter or in metadetect?

**Comment by beckermr** [comment]
I was leaning towards metadetect but pizza cutter makes more sense so let's do that.

**Comment by esheldon** [comment]
it makes sense for our work, but maybe not for others that may want to use the slices.

**Comment by beckermr** [comment]
We got very little agreement on that and so my inclination is to assume people besides us won't be doing using them.
