### ISSUE TITLE
save gaia star data in extension

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#238]
Rather than apply the mask here, store the stars in the file

Move the masking code to https://github.com/beckermr/pizza-cutter-metadetect

**Comment by esheldon** [comment]
Will we have the full wcs available upon reading from the pizza file to convert ra, dec to x, y?

**Comment by esheldon** [comment]
Might be simpler to store the coadd x, y (for the full original coadd) in the pizza file and then all we need is the start_row, start_col for each slice

**Comment by beckermr** [comment]
We can store the converted positions OFC. I save the coadd header WCS in the meds file also.
