### ISSUE TITLE
add code to download and put the gaia files in the configs

### ISSUE THREAD

**Issue by beckermr** [beckermr/pizza-cutter#241]

**Comment by beckermr** [comment]
code to make the file is here: https://github.com/DarkEnergySurvey/MEPipelineAppIntg/commit/b11c4e8a6dd2791856b0fcb1418069ac26f227c2

We may be able to download premade ones from DESDM

**Comment by beckermr** [comment]
gaia file can be gotten via this query

```
select fai.path,fai.filename from desfile d, file_archive_info fai where d.filetype='cat_tile_gaia'  and d.filename like '%v1.fits' and d.filename=fai.filename;
```

**Comment by rgruendl** [comment]
The above will get you all of the catalogs (i.e. O(10k) files... one per tile).

**Comment by beckermr** [comment]
Yes. I adjusted the like statement. I will put it back!
