### ISSUE TITLE
don't symmetrize weights or masks within the GAIA star holes?

### ISSUE THREAD

**Issue by beckermr** [beckermr/pizza-cutter#271]
![mbobs5](https://user-images.githubusercontent.com/5296416/135530495-95b667b0-908d-476e-8afe-0a1ceb0a131b.png)

See the image above. We don't need to interpolate in the area below the star hole because it is masked later anyways.

**Comment by beckermr** [comment]
cc @esheldon

**Comment by esheldon** [comment]
The title is about symmetrization, but the question is about interpolation.

**Comment by beckermr** [comment]
Well we symmetrize and then interpolate any bad pixels. So if we don't symmetrize, then we won't interpolate in the symmetrized locations of the bad pixels.

**Comment by esheldon** [comment]
Is the idea to not symmetrize the star holes, or everything under the star hole too?

**Comment by esheldon** [comment]
Have you run sim tests where you didn't symmetrize the star holes?

**Comment by beckermr** [comment]
Yes. With apodization+expansion it all worked fine.

**Comment by beckermr** [comment]
Basically, once you control for the FFT artifacts and strong masking effects in the response, things are good to go.

**Comment by beckermr** [comment]
That was only high s/n though.
