### ISSUE TITLE
don't use wcs color for piff

### ISSUE THREAD

**Issue by beckermr** [beckermr/pizza-cutter#296]
Following a discussion with Mike here is the correct thing:

> Basically, when drawing the PSF, you should use the same WCS that Piff used when modeling it.  This gives the best estimate of the image-grid profile of a point source for whatever color you tell it to use.  Then when modeling the galaxy, you should use a WCS corresponding to the galaxy color.
So for metacal, we should have done:
Draw PSF onto image with wcs = Pixmappy(g-i=1.6), telling Piff to use color=1.1.
Then give metacal/ngmix a wcs = Pixmappy(g-i=1.1)
For BFD:
Draw PSF onto image with wcs = Pixmappy(g-i=1.6), telling Piff to use color of galaxy.
In BFD, use Pixmappy(g-i=galaxy g-i)

**Comment by beckermr** [comment]
We used the WCS color when drawing the piff image too.

**Comment by rmjarvis** [comment]
The logic of this choice is that when Piff was modeling the PSF, it was given a WCS that fixed the color at 1.6, which matches the mean color of the stars.  We didn't try to use the right WCS for each star separately.  Piff then models the color-dependence of the star profiles in this context, meaning that whatever color dependence is in the WCS got incorporated into the PSF model.

If we then draw this PSF model onto an image whose WCS is set to color=1.6, but tell Piff to use some other color (like a specific galaxy's color or the mean galaxy color) then we'll have Piff's best estimate of what a PSF with that color looks like on this image.

Once you have that image, the galaxy and the PSF are both correct for the galaxy's color on the actual image.  So now you can model both of them using the correct WCS for the galaxy color, and that will be the best estimate model of the galaxy in sky coordinates.
