### ISSUE TITLE
enable using pixmappy for WCS

### ISSUE THREAD

**Issue by beckermr** [beckermr/pizza-cutter#31]
We need to be able to use pixmappy WCS objects.

**Comment by esheldon** [comment]
Here is the code I have to deal with pixmappy

https://github.com/esheldon/ngmixer/blob/master/ngmixer/imageio/desastrom.py

**Comment by esheldon** [comment]
We could add `sky2image` and `image2sky` methods to mimic those in esutil

**Comment by beckermr** [comment]
See my pr for the api changes. I am wrapping this all up
