### ISSUE TITLE
upgrade to fitsio 1.0 

### ISSUE THREAD

**Issue by beckermr** [beckermr/pizza-cutter#36]
Blocked at fitsio processing of header keywords and it stripping blank spaces on the end of strings.

**Comment by esheldon** [comment]
looks like we can't avoid this; what problem is it actually causing for pizza-cutter?

**Comment by esheldon** [comment]
(I was referring to the stripping of header strings)

**Comment by beckermr** [comment]
There is a test that is failing.

**Comment by esheldon** [comment]
I just ran tests with fitsio 1.0.3 and they all passed

**Comment by beckermr** [comment]
Alright. Then we need to change a line in the requirements file to say `fitsio~=1.0`

**Comment by beckermr** [comment]
done.

**Comment by esheldon** [comment]
i'm on it

**Comment by beckermr** [comment]
Ack sorry!
