### ISSUE TITLE
use a temp dir for meds file

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#44]
On gpfs it is very slow to write meds files, better to use a temp dir

**Comment by beckermr** [comment]
The tmpdir stuff is in there already.

**Comment by esheldon** [comment]
Does `des-pizza-cutter` use it?

**Comment by beckermr** [comment]
if you call it right, yes. I forget exactly how to do it.

**Comment by esheldon** [comment]
there is no option for it

**Comment by beckermr** [comment]
ahhh crap you are right. Sorry! I wrote this for running on the coadd sims not for making meds files yet.

**Comment by esheldon** [comment]
no problem
