### ISSUE TITLE
optimize image interpolation

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#64]
currently dominated by the large number of "ok" pixels used for interpolating "bad" pixels in the `CloughTocher2DInterpolator`

```
     3940   86.391    0.022   87.185    0.022 interpolate.py:9(_interp_image)
       83   70.353    0.848   70.353    0.848 _lanczos.py:77(lanczos_resample_two)
      166   42.912    0.259   43.351    0.261 _wcs_utils.py:58(__call__)
        6   30.780    5.130   30.780    5.130 {method 'create_image_hdu' of '_fitsio.FITS' objects}
        8   29.599    3.700   29.719    3.715 _wcs_utils.py:53(__init__)
     1952   21.203    0.011   21.203    0.011 {method 'read' of '_io.FileIO' objects}
      179   13.035    0.073   13.040    0.073 fitslib.py:330(__init__)
       56    9.494    0.170    9.494    0.170 {method 'read_image' of '_fitsio.FITS' objects}
      199    7.891    0.040    7.891    0.040 {method 'normal' of 'mtrand.RandomState' objects}

```

**Comment by beckermr** [comment]
Is that the specific reason (the ok pixels)?

**Comment by esheldon** [comment]
If we could identify a 3 pixel boundary around each bad area then we could greatly reduce the number of good pixels used for the interpolater.

A trivial but not optimal way to do this would be to do a line scan, row wise, and when bad pixels are hit keep track of  the previous 3 pixels, and then when a good pixel is hit keep track of the next 3 pixels.  Then include all such sets in the good pixel set.

This would not include regions +3/-3 columns only rows but it would be very fast to calculate.

**Comment by esheldon** [comment]
I was assuming that is the limiting factor, making the mesh for the good points

**Comment by esheldon** [comment]
(and evaluating on that mesh)

**Comment by beckermr** [comment]
Is the line scan better than simply aggregating pixels via looping over the bad ones and adding good ones around them? Under the assumption there are not a lot of bad pixels, we might touch less data this way, but cache usage would potentially be worse.

**Comment by esheldon** [comment]
right, I was trying to avoid cache misses.

But I think we would have to do better and include +/-3 columns as well. Might still be fairly fast.

We would get dups that way, but we can use `np.unique` to fix that, it is fast enough.

**Comment by beckermr** [comment]
If we can presort the bad pixels by their C index we probably get some cache efficiency back either way, but maybe not enough. Will take testing.
