### ISSUE TITLE
add epoch information to the meds files

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#72]
Things to add

- [x] how many images went into the coadd
- [x] the relative weights of the images
- [ ] the bit mask for each image
- [x] the size of the psf for each image
- [x] which actual image was used
- [x] the approximate bounds in the input SE image
- [x] flags about why other images were excluded

**Comment by beckermr** [comment]
What other data? Maybe the PSF sizes of each epoch?

**Comment by beckermr** [comment]
We could keep the bitmasks for each epoch as well, but this is a lot more data. The ormask probably has enough information in it TBH.

**Comment by esheldon** [comment]
Yeah, the bitmasks compress to nothing. But the meds maker doesn't know how to save epoch for one type and not the other so this would take some development.

**Comment by beckermr** [comment]
Right I forgot about the compression. I am writing the data by hand instead of using the meds maker in the meds repo, so I think we could swing this here if we wanted.

**Comment by esheldon** [comment]
I'm starting a PR for this

**Comment by esheldon** [comment]
nepoch is in now.

**Comment by esheldon** [comment]
what was the idea for psf sizes for each epoch?  Is the worry if some of them were small that went into the psf coadd?

**Comment by beckermr** [comment]
I did not have a specific thing in mind. I was just thinking of stuff we could grab easily. I am happy to close this issue for now, but I thought maybe some forethought into this might be useful.

**Comment by esheldon** [comment]
On thing that might be useful is some idea of the weighting for each image that went in.  What is the effective number of epochs?   This could be gotten from `sum(weights)/max(weights)`

**Comment by esheldon** [comment]
I think for your list, which is one entry per epoch, we might want to add a new extension `epoch_info` or something like that

**Comment by beckermr** [comment]
I was thinking the same thing on the new entry.

**Comment by esheldon** [comment]
I'll have a PR coming on some of these

**Comment by beckermr** [comment]
@esheldon Did you move the nepochs field from the object data to the new epochs_info extension? We should probably do that.

**Comment by beckermr** [comment]
ohhhhh nm. They are stored flat. works for me.

**Comment by beckermr** [comment]
I'm good to close this for now. The individual epochs are a fair bit more work and it is not clear to me that we need them right away. I think we have enough metadata to move ahead for diagnosing problems. 

I am going to go ahead and close this issue. Feel free to reopen @esheldon if you want to add additional things.
