### ISSUE TITLE
run the desmeds prep code also

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#94]
Now that we are committing to storing the info using pizza cutter code, we might as well also run the prep code too

**Comment by beckermr** [comment]
Is this the code that downloads the files?

**Comment by esheldon** [comment]
yes

**Comment by esheldon** [comment]
I plan to replace the `gen-des-pizza-cutter-info` will something like `des-pizza-cutter-prep-tile` that will download the data and generate the info at the same time.
