### ISSUE TITLE
warning in interpolate

### ISSUE THREAD

**Issue by esheldon** [beckermr/pizza-cutter#95]
I got this after the Y3 tapebump andn config changes
```
pizza_cutter/slice_utils/interpolate.py:19: RuntimeWarning: invalid value encountered in sqrt
```

**Comment by beckermr** [comment]
Do you have a minimum working example?

**Comment by beckermr** [comment]
We only hit this code path if we feed None into the interpolation

https://github.com/beckermr/pizza-cutter/blob/master/pizza_cutter/slice_utils/interpolate.py#L197

However, we make a noise image for each CCD that is cached on disk. Thus I don't see how this error was generated.

**Comment by beckermr** [comment]
This whole section of code looks weird. 

https://github.com/beckermr/pizza-cutter/blob/master/pizza_cutter/slice_utils/interpolate.py#L188

We should make feeding a noise image required here and then figure out what breaks maybe.

**Comment by beckermr** [comment]
and I found the bug  - fixing in another PR.
